config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  root :to => 'pages#home'
  resources :users, :only => [:index, :new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :repos
  post '/resources/:id' => 'resources#update'
  resources :resources

  resources :languages

  # get '/resources/:repo_id' => 'resources#index', :as => 'resources'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :language, :optional => true
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :resources
  has_and_belongs_to_many :repos
  has_and_belongs_to_many :users
  has_many :books
end

app/models/repo.rb
class Repo < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :resources
  # before_destroy { resources.clear }
  has_and_belongs_to_many :languages
  has_many :books, :through => :resources

# Map the resource to each Language - accessible from any Repo
  def resources_by_language
    resources.group_by { |r| r.language_ids.first } # group by language if the language is present
  end

end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :language, :optional => true
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :repos
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :repos
  has_and_belongs_to_many :languages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :check_for_login

  def new
    @language = Language.new
  end

  def create
    language = Language.create language_params
    @current_user.languages << language
    redirect_back :fallback_location => root_path
  end

  def edit
    @language = Language.find params[:id]
  end

  def update
    language = Language.find params[:id]
    language.update language_params
    redirect_to language_path
  end

  def destroy
    language = Language.find params[:id]
    language.destroy
    redirect_to root_path
  end

  private
  def language_params
    params.require(:language).permit(:title, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @lang = Language.all
    @language = Language.new
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :check_for_login

  def index
    @repos = Repo.all
  end

  def show
    @repo = Repo.find params[:id]
  end

  def new
    @repo = Repo.new
  end

  def create
    repo = Repo.create repo_params
    @current_user.repos << repo
    redirect_to repo_path(repo.id)
  end

  def edit
    @repo = Repo.find params[:id]
  end

  def update
    repo = Repo.find params[:id]
    repo.update repo_params
    redirect_to repo_path
  end

  def destroy
    repo = Repo.find params[:id]
    repo.destroy
    redirect_to repos_path
  end

  private
  def repo_params
    params.require(:repo).permit(:title)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :check_for_login

  def index
    @resource = Resource.find params[:repo_id]
  end

  def show
    @resource = Resource.find params[:id]
  end

  def new
    @resource = Resource.new
  end

  def create
    resource = Resource.create resource_params
    @current_user.repos.find(params["repo_id"]).resources << resource
    redirect_to repo_path(params["repo_id"])
  end

  def edit
    @resource = Resource.find params[:id]
  end

  def update
    resource = Resource.find params[:id]
    resource.update resource_params
    redirect_to repo_path(params[:repo_id])
  end

  def destroy
    resource = Resource.find params[:id]
    resource.destroy
    redirect_to repo_path(params[:repo_id])
  end

  private
  def resource_params
    params.require(:resource).permit(:title, :url, :language_ids, :form_data)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeconqr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>CodeConqr</title>

  </head>

  <body style="background-image: url('/assets/cool-background.png'); background-size: cover; background-repeat: no-repeat;">
    <div class="container" >
    <nav>
      <%= link_to 'Home', root_path %>
      |
      <% if @current_user.present? %>
        <% if @current_user.admin? %>
          <%= link_to 'All users', users_path %>
          |
        <% end %>
        <%= link_to "Repo's", repos_path %>
        |
        You are logged in as <%= @current_user.email %> -
        <%= link_to "Log out", login_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_path %>
        |
        <%= link_to 'Sign In', login_path %>
      <% end %>
    </nav>
    <div class="bg-dark text-light px-2 rounded" style="opacity: 0.85;">
    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>CodeConqr</h1>

<% if @current_user.present? %>
    <h2>Welcome back <%= @current_user.email %></h2>
<% end %>


<p><span>
There are so many amazing resources available online but it's difficult to keep track of them all.
CodeConqr is here to solve that!
<br>
Track online courses, resources and coding languages with CodeConqr.
</span></p>

<% if @current_user.present? %>
  <h3>Your current languages:</h3>
  <ul>
    <% @lang.each do |language| %>
    <li>
      <%= language.title %>
      <%= image_tag language.image, :class => 'thumb' if language.image.present? %>
      <div><%= link_to "delete", {:controller => "languages", :action => "destroy", :id => language.id }, data: {confirm: 'Are you sure?'}, :method => 'delete' %></div>
    <% end %>
    </li>
  </ul>

  <br>
  <br>
  <br>
  <br>
  <br>

  <ul style="list-style-type:none">

    <%= form_for @language do |f| %>
      <div class="form-group">
  <li><%= f.text_field :title, :required => true, :placeholder => "New Language", :class => 'form-control' %></li>
  <li><%= f.url_field :image, :placeholder => "Image Link", :class => 'form-control' %></li>
    <h5>
      <%= f.submit "Add Language", :class => 'btn btn-primary' %>
      <% end %>
    </h5>
      </div>
  </ul>
<% end %>
<br>

app/views/repos/edit.html.erb
<h1><%= @repo.title %></h1>

<%= form_for @repo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :required => true, :autofocus => true %>

  <%= f.submit %>
<% end %>
<br>

app/views/repos/index.html.erb
<h1>My Repo's</h1>

<% @current_user.repos.each do |repo| %>
  <% if repo.present? %>
    <p>
      Repo:
      <%= link_to repo.title, repo %>
    </p>
  <% end %>
<% end %>


<%= link_to 'New Repo', new_repo_path %>
<br>

app/views/repos/new.html.erb
<h1>New Repository</h1>

<%= form_for @repo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :required => true %>

  <%= f.submit %>
<% end %>
<br>

app/views/repos/show.html.erb
<br>
  <%= form_for @repo do |f| %>
    <div class="form-group input-lg">
<h1><%= f.text_field :title, :required => true, :class => 'form-control' %></h1>
  <h5>
    <%= f.submit "Save", :class => 'btn btn-primary' %>
    <% end %>
  </h5>
    </div>

<% @repo.resources_by_language.each do |id, resources| %>
      <% @language = Language.find(id) %>
      <%= image_tag @language.image, :class => 'thumb' if id.present? %>
      <%= @language.title if id.present? %>
    Resources:
    <p></p>
      <% resources.each do |resource| %>
        <%= link_to resource.title, resource_path(resource.id, :repo_id => @repo.id) %>
        <p></p>
    <% end %>
    <br>
<% end %>


<%= link_to 'New Resource', new_resource_path(:repo_id => @repo.id) %>
<br>
<br>
<br>
<br>
<br>
<br>
<%= button_to 'Delete Repo', @repo, data: {confirm: 'Are you sure?'}, :method => 'delete', :class => 'btn btn-danger' %>
<br>

app/views/resources/edit.html.erb
<h1><%= @resource.title %></h1>

<%= form_for @resource do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :class => 'form-control' %>
  <br>
  <%= f.label :url %>
  <%= f.text_field :url, :required => true, :class => 'form-control' %>
  <br>
  <%= f.label :language_id %>
  <%= f.collection_select :language_ids, Language.all,:id,:title, :class => 'form-control' %>
  <br>
  <%= link_to "Add New Language", root_path %>

  <%= hidden_field_tag :repo_id, params[:repo_id] %>
  <br><br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>
<br>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= form_for @resource do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true, :class => 'form-control' %>

  <%= f.label :url %>
  <%= f.url_field :url, :class => 'form-control' %>

  <%= f.label :language_id %>
  <%= f.collection_select :language_ids, Language.order(:title),:id,:title, :class => 'form-control' %>

  <%= hidden_field_tag :repo_id, params[:repo_id] %>
  <br>
  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>
<br>

app/views/resources/show.html.erb
<h1><%= @resource.title %></h1>

<ul>
  <li>Title: <%= @resource.title %></li>
  <% if @resource.url.present? %>
    <li>URL: <a href="<%= @resource.url %>"><%= @resource.url %></a></li>
  <% end %>
</ul>
<%= link_to 'Edit Resource', edit_resource_path(@resource, :repo_id => params["repo_id"]) %>

<br><br>
<%= form_with do |f| %>
  <trix-editor autofocus=true><%= f.text_field :body, as: :trix_editor, :required => true %></trix-editor>
  <%= f.submit nil, :class => 'btn btn-primary'%>
<% end %>
<br><br>

<%= button_to 'Delete Resource', resource_path(@resource, :repo_id => params["repo_id"]), data: {confirm: 'Are you sure?'}, :method => 'delete', :class => 'btn btn-danger'%>
<br>

app/views/session/new.html.erb
<h1>Sign In</h1>

<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end  %>

<%= form_tag login_path do%>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign in", :class => 'btn btn-primary' %>
<% end %>
<br>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <p><%= user.email %></p>
<% end %>
<br>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :email %>
<%= f.email_field :email, :class => 'form-control'  %>

<%= f.label :password %>
<%= f.password_field :password, :class => 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, :class => 'form-control'  %>

<%= f.submit "Sign up", :class => 'btn btn-primary'  %>
<% end %>
<br>